### ISSUE TITLE
Android获取不到deviceToken

### ISSUE THREAD

**Issue by warrenwyf** [liuchungui/react-native-umeng-push#11]
iOS没问题，Android获取不到，不知道是不是有地方没做对。

React Native版本0.34.0，按照文档排查了几遍似乎没什么问题，但是获取不到deviceToken

**Comment by liuchungui** [comment]
@warrenwyf 
你手机系统是多少啊？我这几天试下看看

**Comment by liuchungui** [comment]
@warrenwyf 不知你试过[Device_token 相关问题整理](http://bbs.umeng.com/thread-15233-1-1.html)这个文档里面说解决方法没？
前面有个同学遇到了因为gradle没更新到1.5而造成获取不到deviceToken

**Comment by warrenwyf** [comment]
@liuchungui 小米和华为荣耀都试过，估计和系统无关。
Device_token相关问题都看了，没能解决。
gradle版本挺高的，2.14.1。
还有什么可能，如何排查？

**Comment by warrenwyf** [comment]
@liuchungui 友盟的后台中Push SDK版本一项是空，这个有影响吗？

**Comment by liuchungui** [comment]
@warrenwyf 这个没太懂你意思啊，我没设置过Push SDK版本，是在哪里设置的？

**Comment by warrenwyf** [comment]
@liuchungui 
![image](https://cloud.githubusercontent.com/assets/860765/18939076/3b801fd6-8630-11e6-9ca5-ccebfced46b3.png)

**Comment by liuchungui** [comment]
@warrenwyf 这个我没设置过，以前都在用，没有影响，我今天中午试试0.34.1在我手机里面是否能获取deviceToken

**Comment by warrenwyf** [comment]
@liuchungui 试了友盟给的Demo 2.8.1L_Beta，是正常的，应该和设备无关。

**Comment by liuchungui** [comment]
@warrenwyf 我刚刚试了0.34.1版本，能收到deviceToken，你包名是否正确？

**Comment by warrenwyf** [comment]
@liuchungui 包名我check了很多遍了，不会错的。包括build.gradle AndroidManifest.xml。包名还有别的地方需要改吗？

**Comment by liuchungui** [comment]
需要改地方有三个：
1、将友盟的app key添加进去
2、将MainApplication继承UmengPushApplication，并添加对应的package
3、添加PushSDK模块

这些步骤文档都有，你的设备是4.x？我的设备是5.1版本的

**Comment by liuchungui** [comment]
@warrenwyf 你直接拿我的Example试试，嗯，我以前用过4.x的设备，能收到

**Comment by warrenwyf** [comment]
@liuchungui 看Example找到原因了，umeng的meta-data没有放到Application标签下导致的。看README以为只要放到manifest下就可以了。

**Comment by liuchungui** [comment]
@warrenwyf 哈哈，这是我的原因，我改下README

**Comment by warrenwyf** [comment]
@liuchungui 非常感谢🙏
