### ISSUE TITLE
集成之后，打包时报错

### ISSUE THREAD

**Issue by maagee** [liuchungui/react-native-umeng-push#23]
报错，好像是SDK的原因
:app:dexRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:dexRelease'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

**Comment by liuchungui** [comment]
@maagee 请问android是多少版本号？你这是在打包的时候报错的？

**Comment by maagee** [comment]
@liuchungui  
好像是这个问题：
finished with non-zero exit value 2
jar包超65KB或者jar冲突

build.gradle 里设置
multiDexEnabled   true  就好了
