### ISSUE TITLE
RCTUmengPush.h file not found

### ISSUE THREAD

**Issue by SpadeGod** [liuchungui/react-native-umeng-push#29]
XCode Version:  8.3.1
ReactNative Version: 0.39.0
platform: IOS

#import RCTUmentPush.h 

提示找不到这个入口文件，但是这个文件存在项目之中

**Comment by SpadeGod** [comment]
解决了，需要为xcode添加一下目录索引就好了

**Comment by zhuxiaozhuworking** [comment]
@SpadeGod 您还有印象怎么建立索引吗  我这里是文件解决了svn冲突之后 怎么样都找不到连接了

**Comment by Kennytian** [comment]
@SpadeGod @zhuxiaozhuworking  解决了，需要为xcode添加一下目录索引就好了，是怎么做的？
