### ISSUE TITLE
退出应用 收到推送无法处理

### ISSUE THREAD

**Issue by zhuchuanwu** [liuchungui/react-native-umeng-push#3]
退出应用 收到推送无法处理，不走
UmengPush.didOpenMessage(message => {
      console.log("didOpenMessage:", message);
    });
改咋处理呢

**Comment by liuchungui** [comment]
你是android还是ios？是哪个版本的？

**Comment by zhuchuanwu** [comment]
ios react-native 是0.25

**Comment by zhuchuanwu** [comment]
不过我的是原生app集成了react-native  这个应该没影响吧？

**Comment by liuchungui** [comment]
@zhuchuanwu 不受影响，我明天看看吧

**Comment by zhuchuanwu** [comment]
可以加我qq吗 1317272927

**Comment by liuchungui** [comment]
已经解决了，你更新看看

**Comment by zhuchuanwu** [comment]
赞
