### ISSUE TITLE
求助，急需用这个功能 MainApplication cannot be cast to com.liuchugui.react_native_umeng_push.UmengPushApplication

### ISSUE THREAD

**Issue by 277850318** [liuchungui/react-native-umeng-push#5]
"react-native": "0.30.0",
"react-native-umeng-push": "^1.0.4"
compileSdkVersion 23
buildToolsVersion "23.0.1"
useLibrary 'org.apache.http.legacy'

![image](https://cloud.githubusercontent.com/assets/8946022/17806292/38cc4342-6636-11e6-9850-5bececfcc6a9.png)
@liuchungui 

编译什么都过了 运行的时候报这个错
求助，急需用这个功能

**Comment by liuchungui** [comment]
@277850318 不好意思啊，今天才看到，请问你解决了么？

**Comment by 277850318** [comment]
解决了 遇到新的问题了  程序在后台能收到通知切状态栏显示  程序在前台运行能收到通知 但是不会显示在状态栏

**Comment by liuchungui** [comment]
@277850318 这是我内部控制这么显示的，就是在前台的时候直接接收通知，不在顶部显示通知栏了

**Comment by duguying** [comment]
@277850318 请问你是怎么解决的呢

**Comment by duguying** [comment]
知道了， MainApplication extends UmengPushApplication，README文档上有写
