### ISSUE TITLE
通知被忽略

### ISSUE THREAD

**Issue by 277850318** [liuchungui/react-native-umeng-push#6]
程序在后台能收到通知且能状态栏显示 
程序在前台运行能收到通知 但是不会显示在状态栏
![image](https://cloud.githubusercontent.com/assets/8946022/17929158/3bdaf8fe-6a31-11e6-9da4-646dd41ce2de.png)
![image](https://cloud.githubusercontent.com/assets/8946022/17929159/3d7f43a4-6a31-11e6-9314-a15ddda2c441.png)

**Comment by liuchungui** [comment]
你意思前台通知在顶部没有显示吧？这个是我内部特意忽略的，这几天我看一下改改

**Comment by 277850318** [comment]
是的 就是这个问题   。。。。。希望能早点修复下，着急用了

**Comment by 277850318** [comment]
找到那行代码了 不错

**Comment by liuchungui** [comment]
@277850318 改好了？
你可以改了提交一个commit

**Comment by 277850318** [comment]
这不是个BUG  在当前应用中不用显示通知 只不过我这边需求不一样而已

**Comment by shiqian123** [comment]
@liuchungui  最好加参数配置一下，有的需求是需要app在前台运行的时候显示推送有的不需要 😆

**Comment by qubangliuhui** [comment]
您好，求告知哪行代码

**Comment by qubangliuhui** [comment]
@277850318
